// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Convert(arg1:number,arg2:string,arg3:string):Promise<number>;

export function GetUnits():Promise<Record<string, number>>;
